### ISSUE TITLE
future work?

### ISSUE THREAD

**Issue by hcientist** [Zamua/less-java#10]
if you've already decided on some of the future work, maybe they could appear here as issues (even with help-wanted label)?

what would you think about the (common in similar types of projects) ability to drop in to java arbitrarily in a less-java file?

**Comment by hcientist** [comment]
found it in wiki: https://github.com/Zamua/less-java/wiki

**Comment by lam2mo** [comment]
This isn't really an "issue" as written. If you'd like to add an issue as a feature request for drop-in Java feel free to do so, although I think I agree with Zamua that it doesn't really have a great use-case in the context of 149. By the time they're ready to write "real Java" they should just be writing actual Java programs.
